# Generated by Django 4.1.5 on 2023-01-12 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('post_tag', models.CharField(default='', max_length=40)),
                ('post_title', models.CharField(default='', max_length=40)),
                ('post_content', models.TextField(default='', max_length=10000)),
                ('timestamp', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
