# Generated by Django 4.1.5 on 2023-01-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_posts_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_desc',
            field=models.CharField(default='', max_length=400),
        ),
        migrations.AddField(
            model_name='post',
            name='post_thumbnail',
            field=models.ImageField(default='', upload_to='Images'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
